$?

diff --git a/.github/workflows/build-release-upload-ci.yml b/.github/workflows/build-release-upload-ci.yml
--- a/.github/workflows/build-release-upload-ci.yml
+++ b/.github/workflows/build-release-upload-ci.yml
@@ -401,8 +401,9 @@ jobs:
           echo "conclusion: ${{ steps.delete-solution-old-version-directory-from-azure-storage.conclusion }}"
           echo "outcome: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outcome }}"
           echo "error: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.error }}"
-          echo "error: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ERROR }}"
-          echo "error: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ErrorCode }}"
+          echo "ERRPR: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ERROR }}"
+          echo "ErrorCode: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ErrorCode }}"
+          echo "error code: $?"
 
       - name: Warning
         if: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outcome == 'failure' }}
