fail-not-exist

diff --git a/.github/workflows/build-release-upload-ci.yml b/.github/workflows/build-release-upload-ci.yml
--- a/.github/workflows/build-release-upload-ci.yml
+++ b/.github/workflows/build-release-upload-ci.yml
@@ -407,15 +407,16 @@ jobs:
           inlineScript: |
             az storage fs directory delete \
             --yes \
+            --fail-not-exist \
             --name "${{ needs.solution-configuration.outputs.solution-unique-name }}" \
             --file-system "${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
             --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
             --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
 
-      - name: SHOW OUTPUTS
-        if: ${{ failure() }}
-        run: |
-          echo "failure: $?"
+      # - name: SHOW OUTPUTS
+      #   if: ${{ failure() }}
+      #   run: |
+      #     echo "failure: $?"
 
       # - name: SHOW OUTPUTS
       #   run: |
