test check path exists

diff --git a/.github/workflows/build-release-upload-ci.yml b/.github/workflows/build-release-upload-ci.yml
--- a/.github/workflows/build-release-upload-ci.yml
+++ b/.github/workflows/build-release-upload-ci.yml
@@ -382,6 +382,23 @@ jobs:
           name: ${{ needs.solution-configuration.outputs.solution-unique-name }}_${{ needs.solution-configuration.outputs.solution-parsed-version }}_artifacts
           path: github-action/solution/
 
+      - name: Check if directory already exists
+        id: check-if-directory-already-exists
+        uses: Azure/cli@v1
+        with:
+          inlineScript: |
+            az storage fs exists \
+            --path "${{ needs.solution-configuration.outputs.solution-unique-name }}" \
+            --file-system "${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
+            --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
+            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
+            --output tsv
+
+      - name: PRINT RESULT
+        if: ${{ success() }}
+        run: |
+          echo "The directory already exists: ${{ steps.check-if-directory-already-exists.outputs.result }}"
+
       - name: Delete solution old version directory from Azure storage (if exists)
         id: delete-solution-old-version-directory-from-azure-storage
         if: ${{ inputs.delete-old-version-from-azure == true }}
@@ -394,21 +411,21 @@ jobs:
             --name "${{ needs.solution-configuration.outputs.solution-unique-name }}" \
             --file-system "${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
             --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
-            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" || true
+            --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
 
-      - name: SHOW OUTPUTS
-        if: ${{ failure() }}
-        run: |
-          echo "failure: $?"
+      # - name: SHOW OUTPUTS
+      #   if: ${{ failure() }}
+      #   run: |
+      #     echo "failure: $?"
 
-      - name: SHOW OUTPUTS
-        run: |
-          echo "conclusion: ${{ steps.delete-solution-old-version-directory-from-azure-storage.conclusion }}"
-          echo "outcome: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outcome }}"
-          echo "error: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.error }}"
-          echo "ERRPR: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ERROR }}"
-          echo "ErrorCode: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ErrorCode }}"
-          echo "error code: $?"
+      # - name: SHOW OUTPUTS
+      #   run: |
+      #     echo "conclusion: ${{ steps.delete-solution-old-version-directory-from-azure-storage.conclusion }}"
+      #     echo "outcome: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outcome }}"
+      #     echo "error: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.error }}"
+      #     echo "ERROR: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ERROR }}"
+      #     echo "ErrorCode: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outputs.ErrorCode }}"
+      #     echo "error code: $?"
 
       - name: Warning
         if: ${{ steps.delete-solution-old-version-directory-from-azure-storage.outcome == 'failure' }}
